export const data = [
  {
    overview:
      'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    release_date: '2022-03-01',
    adult: false,
    backdrop_path: '/tRS6jvPM9qPrrnx2KRp3ew96Yot.jpg',
    genre_ids: [80, 9648, 53],
    vote_count: 4161,
    original_language: 'en',
    original_title: 'The Batman',
    poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    vote_average: 7.8,
    video: false,
    id: 414906,
    title: 'The Batman',
    popularity: 8195.597,
    media_type: 'movie',
  },
  {
    backdrop_path: '/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
    genre_ids: [28, 12, 10751],
    original_language: 'en',
    original_title: 'Uncharted',
    poster_path: '/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg',
    video: false,
    vote_average: 7.2,
    vote_count: 1563,
    overview:
      'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
    release_date: '2022-02-10',
    title: 'Uncharted',
    id: 335787,
    adult: false,
    popularity: 9026.362,
    media_type: 'movie',
  },
  {
    genre_ids: '[10749, 18]',
    original_language: 'pl',
    original_title: '365 Days: This Day',
    poster_path: '/3UPXQtdWLdOkU6zHNP3gIZ2M4K4.jpg',
    video: false,
    vote_average: 6.1,
    vote_count: 242,
    overview:
      "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
    release_date: '2022-04-27',
    id: 829557,
    title: '365 Days: This Day',
    adult: false,
    backdrop_path: '/zBG5Mg29NH9xxpWMMG7BIvKwYhL.jpg',
    popularity: 4922.217,
    media_type: 'movie',
  },
  {
    id: 634649,
    adult: false,
    backdrop_path: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
    title: 'Spider-Man: No Way Home',
    genre_ids: '[28, 12, 878]',
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    video: false,
    vote_average: 8.1,
    overview:
      'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    release_date: '2021-12-15',
    vote_count: 12294,
    popularity: 4716.995,
    media_type: 'movie',
  },
  {
    genre_ids: '[28, 53, 80]',
    original_language: 'en',
    original_title: 'Ambulance',
    poster_path: '/zT5ynZ0UR6HFfWQSRf2uKtqCyWD.jpg',
    id: 763285,
    video: false,
    vote_average: 6.8,
    overview:
      "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
    release_date: '2022-03-16',
    title: 'Ambulance',
    vote_count: 398,
    adult: false,
    backdrop_path: '/192vHmAPbk5esL34XMKZ1YLGFjr.jpg',
    popularity: 1619.597,
    media_type: 'movie',
  },
  {
    title: 'Doctor Strange in the Multiverse of Madness',
    genre_ids: '[14, 28, 12]',
    original_language: 'en',
    original_title: 'Doctor Strange in the Multiverse of Madness',
    poster_path: '/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
    video: false,
    vote_average: 7,
    overview:
      'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
    release_date: '2022-05-04',
    vote_count: 22,
    id: 453395,
    adult: false,
    backdrop_path: '/ndCSoasjIZAMMDIuMxuGnNWu4DU.jpg',
    popularity: 967.115,
    media_type: 'movie',
  },
  {
    genre_ids: '[16, 35, 28, 10751, 80]',
    original_language: 'en',
    original_title: 'The Bad Guys',
    poster_path: '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg',
    video: false,
    vote_average: 7.3,
    vote_count: 139,
    overview:
      'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.',
    release_date: '2022-03-17',
    id: 629542,
    title: 'The Bad Guys',
    adult: false,
    backdrop_path: '/fEe5fe82qHzjO4yej0o79etqsWV.jpg',
    popularity: 813.826,
    media_type: 'movie',
  },
  {
    original_title: 'Sonic the Hedgehog 2',
    poster_path: '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
    video: false,
    id: 675353,
    overview:
      'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
    release_date: '2022-03-30',
    vote_count: 786,
    adult: false,
    backdrop_path: '/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
    vote_average: 7.6,
    genre_ids: '[28, 878, 35, 10751]',
    title: 'Sonic the Hedgehog 2',
    original_language: 'en',
    popularity: 4056.245,
    media_type: 'movie',
  },
  {
    id: 406759,
    video: false,
    vote_average: 6.5,
    overview:
      'A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.',
    release_date: '2022-02-03',
    title: 'Moonfall',
    adult: false,
    backdrop_path: '/x747ZvF0CcYYTTpPRCoUrxA2cYy.jpg',
    vote_count: 865,
    genre_ids: '[28, 12, 878]',
    poster_path: '/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg',
    original_language: 'en',
    original_title: 'Moonfall',
    popularity: 2291.114,
    media_type: 'movie',
  },
  {
    genre_ids: '[14, 12]',
    original_language: 'en',
    original_title: 'Fantastic Beasts: The Secrets of Dumbledore',
    poster_path: '/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg',
    video: false,
    adult: false,
    backdrop_path: '/wdjdHBDwmynWUrJcNzS24uegvK5.jpg',
    vote_average: 6.8,
    vote_count: 829,
    title: 'Fantastic Beasts: The Secrets of Dumbledore',
    release_date: '2022-04-06',
    overview:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    id: 338953,
    popularity: 1026.105,
    media_type: 'movie',
  },
  {
    video: false,
    vote_average: 6.5,
    overview:
      'Belgian sleuth Hercule Poirot boards a glamorous river steamer with enough champagne to fill the Nile. But his Egyptian vacation turns into a thrilling search for a murderer when a picture-perfect couple’s idyllic honeymoon is tragically cut short.',
    id: 505026,
    title: 'Death on the Nile',
    adult: false,
    backdrop_path: '/lRbDyjI7HEaXxflFQbYpqHRGFBJ.jpg',
    genre_ids: '[80, 18, 9648, 53]',
    vote_count: 1534,
    original_language: 'en',
    original_title: 'Death on the Nile',
    poster_path: '/kVr5zIAFSPRQ57Y1zE7KzmhzdMQ.jpg',
    release_date: '2022-02-09',
    popularity: 404.488,
    media_type: 'movie',
  },
  {
    overview:
      'A woman falls victim to a dominant mafia boss, who imprisons her and gives her one year to fall in love with him.',
    release_date: '2020-02-07',
    id: 664413,
    adult: false,
    backdrop_path: '/isBjNHBblzxrzHrAtRbjgkYzAut.jpg',
    genre_ids: '[10749, 18]',
    vote_count: 6762,
    original_language: 'pl',
    original_title: '365 dni',
    poster_path: '/6KwrHucIE3CvNT7kTm2MAlZ4fYF.jpg',
    title: '365 Days',
    video: false,
    vote_average: 7,
    popularity: 217.863,
    media_type: 'movie',
  },
  {
    genre_ids: '[16, 10751, 35, 14]',
    original_language: 'en',
    original_title: 'Turning Red',
    poster_path: '/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg',
    video: false,
    vote_average: 7.4,
    vote_count: 1980,
    overview:
      'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.',
    release_date: '2022-03-10',
    id: 508947,
    title: 'Turning Red',
    adult: false,
    backdrop_path: '/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg',
    popularity: 3513.967,
    media_type: 'movie',
  },
  {
    original_title: 'Silverton Siege',
    poster_path: '/5HruMN0vvl84AqD7sCDXFNO4RhP.jpg',
    video: false,
    vote_average: 6.7,
    overview:
      'After a failed sabotage mission, a trio of anti-apartheid freedom fighters ends up in a tense bank hostage situation. Based on a true story.',
    release_date: '2022-04-27',
    vote_count: 26,
    adult: false,
    backdrop_path: '/xzLOQjF1w4og963lxsGJwMhPbZ.jpg',
    title: 'Silverton Siege',
    genre_ids: '[28, 80, 18]',
    id: 951470,
    original_language: 'en',
    popularity: 200.516,
    media_type: 'movie',
  },
  {
    genre_ids: '[27, 53]',
    original_language: 'en',
    original_title: 'X',
    poster_path: '/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg',
    id: 760104,
    vote_average: 6.9,
    overview:
      'In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.',
    release_date: '2022-03-17',
    title: 'X',
    vote_count: 286,
    adult: false,
    backdrop_path: '/tGVKZ1zunNDk6ztEBXgtFWPxpaX.jpg',
    video: false,
    popularity: 114.466,
    media_type: 'movie',
  },
  {
    video: false,
    vote_average: 7,
    overview:
      'Leonard is an English tailor who used to craft suits on London’s world-famous Savile Row. After a personal tragedy, he’s ended up in Chicago, operating a small tailor shop in a rough part of town where he makes beautiful clothes for the only people around who can afford them: a family of vicious gangsters.',
    id: 799876,
    title: 'The Outfit',
    adult: false,
    backdrop_path: '/2n95p9isIi1LYTscTcGytlI4zYd.jpg',
    genre_ids: '[18, 53, 80]',
    vote_count: 161,
    original_language: 'en',
    original_title: 'The Outfit',
    poster_path: '/ieOVuwnoFC49m7bekmdQ4AynciS.jpg',
    release_date: '2022-02-25',
    popularity: 2752.077,
    media_type: 'movie',
  },
  {
    poster_path: '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg',
    video: false,
    vote_average: 7.7,
    overview:
      "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    release_date: '2022-04-07',
    vote_count: 370,
    adult: false,
    backdrop_path: '/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg',
    title: 'The Northman',
    genre_ids: '[28, 12, 14, 53]',
    id: 639933,
    original_language: 'en',
    original_title: 'The Northman',
    popularity: 547.196,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/iSsSvXsCTfDSOY8wvJWms616w3I.jpg',
    genre_ids: '[27, 53, 18]',
    original_language: 'en',
    original_title: 'Choose or Die',
    poster_path: '/rEHZjZmpcQF2Z9tJfWuPNZzof8j.jpg',
    video: false,
    vote_average: 5.3,
    vote_count: 280,
    overview:
      'In pursuit of an unclaimed $125,000 prize, a broke college dropout decides to play an obscure, 1980s survival computer game. But the game curses her, and she’s faced with dangerous choices and reality-warping challenges. After a series of unexpectedly terrifying moments, she realizes she’s no longer playing for the money but for her life.',
    release_date: '2022-04-15',
    title: 'Choose or Die',
    id: 838484,
    popularity: 62.904,
    media_type: 'movie',
  },
  {
    id: 294793,
    video: false,
    vote_average: 6,
    overview:
      'When the CIA discovers one of its agents leaked information that cost more than 100 people their lives, veteran operative Henry Pelham is assigned to root out the mole with his former lover and colleague Celia Harrison.',
    release_date: '2022-04-08',
    title: 'All the Old Knives',
    adult: false,
    backdrop_path: '/xicKILMzPn6XZYCOpWwaxlUzg6S.jpg',
    vote_count: 187,
    genre_ids: '[53, 28]',
    poster_path: '/g4tMniKxol1TBJrHlAtiDjjlx4Q.jpg',
    original_language: 'en',
    original_title: 'All the Old Knives',
    popularity: 1690.875,
    media_type: 'movie',
  },
  {
    genre_ids: '[16, 12, 878]',
    original_language: 'ja',
    original_title: 'バブル',
    poster_path: '/kk28Lk8oQBGjoHRGUCN2vxKb4O2.jpg',
    video: false,
    vote_average: 0,
    vote_count: 0,
    overview:
      'In an abandoned Tokyo overrun by bubbles and gravitational abnormalities, one gifted young man has a fateful meeting with a mysterious girl.',
    release_date: '2022-04-28',
    id: 912598,
    title: 'Bubble',
    adult: false,
    backdrop_path: '/a8Q2g0g7XzAF6gcB8qgn37ccb9Y.jpg',
    popularity: 43.023,
    media_type: 'movie',
  },
];
